services:
  server:
    depends_on:
      - db
    container_name: tapko_bot_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerFile
      no_cache: true
      tags:
        - tapko_bot:1.0
    networks:
      - tapko_bot_net
    environment:
      - TGBOT_KEY=<TGBOT_KEY>
      - DB_NAME=tapok_bot
      - DB_PASSWORD=<DB_PASS>
      - DB_USER=tapok
      - DB_HOST=db
      - DB_PORT=5432
      - AUTO_HOUR = "10"
      - AUTO_MINUTE = "10"
      - TZ = "Europe/Moscow"
  db:
    restart: unless-stopped
    container_name: tapko_bot_db
    image: postgres:17.4-bookworm
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tapok
      - POSTGRES_PASSWORD=<DB_PASS>
      - POSTGRES_DB=tapko_bot
      - TZ = "Europe/Moscow"
    networks:
      - tapko_bot_net

networks:
  tapko_bot_net:
        